all: addition_subtraction.rs multiplication_division.rs fibonacci-sequence.rs
	rustc addition_subtraction.rs
	rustc fibonacci-sequence.rs
	rustc multiplication_division.rs

clean:
	@rm -rf addition_subtraction
	@rm -rf fibonacci-sequence
	@rm -rf multiplication_division
